apiVersion: v1
kind: Namespace
metadata:
  name: resources
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap
  namespace: resources
  labels:
    testname: configmap
data:
  not: relevant
