apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-app
  namespace: examples-simple
  labels:
    app: example-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: example-app
  template:
    metadata:
      labels:
        app: example-app
    spec:
      containers:
      - name: example-container
        image: alpine:latest
        command: ["sh", "-c", "while true; do echo Hello, Kubernetes!; sleep 10; done"]
